Show loading notification (#35)
* Play/queue indicators in playlist

* Play/queue notifications working

* Working track progress bar

* Log song completed event

* Better playlist item layout

* Set indeterminate on queued progress bar

* Attempt at using donut progress

* Remove custom: prefix

* Progress bar looking good

* Convert from event-based to mvc

* Make percentages update

* Convert tabs to spaces

* Use indexInTorrent

* Add missing callback

* Fix for RuntimeException

06-24 14:08:12.869  3819  3819 E AndroidRuntime:
java.lang.RuntimeException: Error receiving broadcast Intent {
act=com.github.funkyg.funkytunes.pause flg=0x10000010
pkg=com.github.funkyg.funkytunes bnds=[116,308][212,404] } in
com.github.funkyg.funkytunes.service.NotificationHandler@d748ec2
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
android.os.Handler.handleCallback(Handler.java:751)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
android.os.Handler.dispatchMessage(Handler.java:95)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
android.os.Looper.loop(Looper.java:154)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
android.app.ActivityThread.main(ActivityThread.java:6077)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
java.lang.reflect.Method.invoke(Native Method)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
06-24 14:08:12.869  3819  3819 E AndroidRuntime: Caused by:
java.lang.IllegalArgumentException: Receiver not registered:
com.github.funkyg.funkytunes.service.MusicService$becomingNoisyReceiver$1@9fd1bbb
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1007)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1358)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:608)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
com.github.funkyg.funkytunes.service.MusicService.playbackStopped(MusicService.kt:122)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
com.github.funkyg.funkytunes.service.MusicService.pause(MusicService.kt:111)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
com.github.funkyg.funkytunes.service.NotificationHandler.onReceive(NotificationHandler.kt:108)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        at
android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
06-24 14:08:12.869  3819  3819 E AndroidRuntime:        ... 7 more

* Prevent flickering the loading notification

* Attempt at removing flickering undeterminate notification

* Attempt at removing flickering undeterminate notification

* Attempt at removing flickering undeterminate notification

* Center vertically the loading indicators

* Removed the pause indicator

* Pause idicator working

* Pass indexInTorrent explicitly

* Fixed lint errors and hardcoded build tools version